CREATE TABLE characters (
  "charId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "charName" TEXT NOT NULL,
  "charRace" TEXT NOT NULL,
  "charClass" TEXT NOT NULL,
  "charDesc" TEXT,
  "dateCreated" TIMESTAMP DEFAULT now() NOT NULL
);