CREATE TABLE dnd_users (
  "userId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "userName" TEXT NOT NULL UNIQUE,
  "fullName" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "nickname" TEXT,
  "dateCreated" TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE characters
  ADD COLUMN
    "userId" INTEGER REFERENCES dnd_users("userId")
    ON DELETE SET NULL;