ALTER TABLE characters
  ADD COLUMN "strength" INTEGER DEFAULT 10,
  ADD COLUMN "dexterity" INTEGER DEFAULT 10,
  ADD COLUMN "constitution" INTEGER DEFAULT 10,
  ADD COLUMN "intelligence" INTEGER DEFAULT 10,
  ADD COLUMN "wisdom" INTEGER DEFAULT 10,
  ADD COLUMN "charisma" INTEGER DEFAULT 10;